version: "2.0"

services:
  admin_app:
    build: .
    restart: always
    environment:
      NODE_ENV: production
      APP_SESSION: "123456"
      JWT_KEY: "ZXZvbHZpdF9wYWNhc21heW9fZ2VzdGlvbl9kb2N1bWVudGFyaWFfYXBwX2JhY2tlbmRfMjAxOQ=="
      APP_PORT: 3000
      APP_URL: ""
      DB_DIALECT: "mysql"
      DB_PORT: 25060
      DB_HOST: "db-mysql-sfo2-95142-do-user-7952586-0.b.db.ondigitalocean.com"
      DB_USER: doadmin
      DB_PASSWORD: uyess7q2i1sguoql
      DB_DATABASE: frsiaaatr_db
      GCP_KEY_FILE: "../../config/focused-evening-283407-9fa3131fac35.json"
      GCP_PROJECT_ID: focused-evening-283407
      GCP_BUCKET_NAME: frsiaaatr-bucket
    ports:
      - "3000:3000"
    container_name: frsiaaatr_admin
